# set the name for the project
name: template

services:
  ingress:
    image: netsos/rhit-netsec:latest
    container_name: ingress
    hostname: ingress
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      dmz:
        ipv4_address: 10.10.0.2
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

  internal-fw:
    image: netsos/rhit-netsec:latest
    container_name: internal-fw
    hostname: internal-fw
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      dmz:
        ipv4_address: 10.10.0.3 
      itnl:
        ipv4_address: 10.10.1.3
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

  internal-gw:
    image: netsos/rhit-netsec:latest
    container_name: internal-gw
    hostname: internal-gw
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      itnl:
        ipv4_address: 10.10.1.2
      usr:
        ipv4_address: 10.10.2.2
      srv:
        ipv4_address: 10.10.3.2
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

  dmz-srv:
    image: netsos/rhit-netsec:latest
    container_name: dmz-srv
    hostname: dmz-srv
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      dmz:
        ipv4_address: 10.10.0.5
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

  hostA:
    image: netsos/rhit-netsec:latest
    container_name: hostA
    hostname: hostA
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      usr:
        ipv4_address: 10.10.2.5
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "


  hostB:
    image: netsos/rhit-netsec:latest
    container_name: hostB
    hostname: hostB
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      usr:
        ipv4_address: 10.10.2.6
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

  database:
    image: netsos/rhit-netsec:latest
    container_name: database
    hostname: database
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      srv:
        ipv4_address: 10.10.3.5
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

  mail-srv:
    image: netsos/rhit-netsec:latest
    container_name: mail-srv
    hostname: mail-srv
    working_dir: /volumes/
    tty: true
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      srv:
        ipv4_address: 10.10.3.6
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

networks:
  dmz:
    name: dmz
    ipam:
      config:
        - subnet: 10.10.0.0/24
  itnl:
    name: itnl
    ipam:
      config:
        - subnet: 10.10.1.0/24
  usr:
    name: usr
    ipam:
      config:
        - subnet: 10.10.2.0/24
  srv:
    name: srv
    ipam:
      config:
        - subnet: 10.10.3.0/24
